version: '3'

services:
  backend:
    build:
      dockerfile: dockerfile/backend.dockerfile
    ports:
      - "8888:8888"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "8001:8001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server --console-address ":8001" /data


volumes:
  minio_storage: {}